package mvc.view;

import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import mvc.model.basicTypes.Administrator;
import mvc.model.basicTypes.Customer;
import mvc.model.basicTypes.ItemInOrder;
import mvc.model.basicTypes.Order;
import mvc.model.basicTypes.SimpleCustomer;

public class AdministratorGUI extends javax.swing.JFrame {

	/**
	 * Creates new form AdministratorGUI
	 */
	public AdministratorGUI() {
		initComponents();
		init();
	}
	
	public void init() {
		this.setLocationRelativeTo(null);
		this.setResizable(false);
		showAllUsers();
	}

	public void showAllUsers() {
		//**********************************************************************
		Administrator administrator = Administrator.getInstance();
		List<SimpleCustomer> customers = administrator.getCustomers();
		// if no customer is found, we do nothing
		if (customers == null)
			return;
		
		userInfoScrollPane.getVerticalScrollBar().setUnitIncrement(16);
		
		for (SimpleCustomer customer : customers)
			System.out.println(customer);
		
		// add the items in the order to the GUI
		GridBagConstraints gbc = new GridBagConstraints();
		gbc.gridx = 0;
		gbc.fill = GridBagConstraints.NONE;
		gbc.anchor = GridBagConstraints.PAGE_START;
		gbc.insets = new Insets(2, 2, 2, 2);
		for (SimpleCustomer customer : customers) {
			gbc.gridy = userInfoPanel.getComponentCount();
			userInfoPanel.add(new UserInfoPanel(customer), gbc);
		}
		
		//**********************************************************************
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userInfoScrollPane = new javax.swing.JScrollPane();
        userInfoPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setText("View information of all customers");

        userInfoPanel.setLayout(new java.awt.GridBagLayout());
        userInfoScrollPane.setViewportView(userInfoPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel1)
                .addContainerGap(227, Short.MAX_VALUE))
            .addComponent(userInfoScrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userInfoScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel userInfoPanel;
    private javax.swing.JScrollPane userInfoScrollPane;
    // End of variables declaration//GEN-END:variables
}
