/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.view;

import javax.swing.ImageIcon;
import mvc.model.basicTypes.Product;

/**
 *
 * @author bohao
 */
public class ProductItemPanel extends javax.swing.JPanel {
	private final Product product;
	private final CustomerGUI customerGUI;
	
	public ProductItemPanel(CustomerGUI customerGUI, Product product) {
		this.customerGUI = customerGUI;
		this.product = product;
		initComponents();
		init();
	}

	private void init() {
		ImageIcon img = new ImageIcon(getClass().getResource(
				product.getSmallImageUrl()));
		imageLabel.setIcon(img);
		nameLabel.setText("<html>" + product.getName() + "</html>");
		storeValueLabel.setText(product.getStore());
		categoryValueLabel.setText(product.getCategory());
		shortDescriptionValueLabel.setText(
				"<html>" + product.getShortDescription() + "</html>");
		priceValueLabel.setText("" + product.getPrice());
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        storeLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        shortDescriptoinLabel = new javax.swing.JLabel();
        gbpLabel = new javax.swing.JLabel();
        priceValueLabel = new javax.swing.JLabel();
        shortDescriptionValueLabel = new javax.swing.JLabel();
        categoryValueLabel = new javax.swing.JLabel();
        viewDetailedInfoButton = new javax.swing.JButton();
        AddToCartButton = new javax.swing.JButton();
        storeValueLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        setPreferredSize(new java.awt.Dimension(750, 400));

        imageLabel.setBorder(null);

        nameLabel.setBorder(null);
        nameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        categoryLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        categoryLabel.setText("Category:");

        storeLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        storeLabel.setText("Store:");

        priceLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(219, 40, 48));
        priceLabel.setText("Price:");

        shortDescriptoinLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        shortDescriptoinLabel.setText("Short description:");

        gbpLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        gbpLabel.setForeground(new java.awt.Color(114, 176, 65));
        gbpLabel.setText("GBP");

        priceValueLabel.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        priceValueLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        priceValueLabel.setBorder(null);
        priceValueLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        priceValueLabel.setRequestFocusEnabled(false);

        shortDescriptionValueLabel.setBorder(null);

        categoryValueLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        categoryValueLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        categoryValueLabel.setBorder(null);

        viewDetailedInfoButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        viewDetailedInfoButton.setText("View detailed information");
        viewDetailedInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailedInfoButtonActionPerformed(evt);
            }
        });

        AddToCartButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        AddToCartButton.setText("Add to Cart");
        AddToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToCartButtonActionPerformed(evt);
            }
        });

        storeValueLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        storeValueLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        storeValueLabel.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(categoryLabel)
                                    .addComponent(storeLabel))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(categoryValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(storeValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(shortDescriptionValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(priceLabel)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(gbpLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(priceValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(shortDescriptoinLabel)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(viewDetailedInfoButton)
                                .addGap(311, 311, 311)
                                .addComponent(AddToCartButton)))
                        .addGap(0, 88, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(shortDescriptoinLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(categoryValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoryLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(storeLabel)
                            .addComponent(storeValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shortDescriptionValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(priceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(gbpLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(priceValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewDetailedInfoButton)
                    .addComponent(AddToCartButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToCartButtonActionPerformed
		customerGUI.addToCart(product);
    }//GEN-LAST:event_AddToCartButtonActionPerformed

    private void viewDetailedInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailedInfoButtonActionPerformed
		customerGUI.showDetailedInfo(product);		
    }//GEN-LAST:event_viewDetailedInfoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCartButton;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel categoryValueLabel;
    private javax.swing.JLabel gbpLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceValueLabel;
    private javax.swing.JLabel shortDescriptionValueLabel;
    private javax.swing.JLabel shortDescriptoinLabel;
    private javax.swing.JLabel storeLabel;
    private javax.swing.JLabel storeValueLabel;
    private javax.swing.JButton viewDetailedInfoButton;
    // End of variables declaration//GEN-END:variables
}
