/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.view;

import javax.swing.ImageIcon;
import mvc.model.basicTypes.Product;

/**
 *
 * @author bohao
 */
public class ProductDetailedInfoPanel extends javax.swing.JPanel {

	private final Product product;
	private final CustomerGUI customerGUI;
	

	public ProductDetailedInfoPanel(CustomerGUI customerGUI, Product product) {
		
		this.customerGUI = customerGUI;
		this.product = product;
		
		initComponents();

		ImageIcon img = new ImageIcon(getClass().getResource(
				product.getBigImageUrl()));
		imageLabel.setIcon(img);
		nameValueLabel.setText("<html>" + product.getName() + "</html>");
		storeValueLabel.setText(product.getStore());
		categoryValueLabel.setText(product.getCategory());
		shortDescriptionValueLabel.setText(
				"<html>" + product.getShortDescription() + "</html>");
		longDescriptionValueLabel.setText(
				"<html>" + product.getLongDescription() + "</html>");
		priceValueLabel.setText("" + product.getPrice() + "  GBP");
		weightValueLabel.setText(""+ product.getWeight() + "  grams");
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        storeLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        shortDescriptionLabel = new javax.swing.JLabel();
        longDescriptionLabel = new javax.swing.JLabel();
        AddToCartButton = new javax.swing.JButton();
        priceLabel = new javax.swing.JLabel();
        priceValueLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        shortDescriptionValueLabel = new javax.swing.JLabel();
        categoryValueLabel = new javax.swing.JLabel();
        nameValueLabel = new javax.swing.JLabel();
        storeValueLabel = new javax.swing.JLabel();
        longDescriptionValueLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        weightValueLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        setPreferredSize(new java.awt.Dimension(750, 1500));

        storeLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        storeLabel.setText("Store:");

        nameLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        nameLabel.setText("Name:");

        weightLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        weightLabel.setText("Weight:");

        shortDescriptionLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        shortDescriptionLabel.setText("Short description:");

        longDescriptionLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        longDescriptionLabel.setText("Long description");

        AddToCartButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        AddToCartButton.setText("Add to Cart");
        AddToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToCartButtonActionPerformed(evt);
            }
        });

        priceLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(219, 40, 48));
        priceLabel.setText("Price:");

        priceValueLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        priceValueLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        priceValueLabel.setBorder(null);

        imageLabel.setBorder(null);

        shortDescriptionValueLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        shortDescriptionValueLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        shortDescriptionValueLabel.setBorder(null);

        categoryValueLabel.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        categoryValueLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        categoryValueLabel.setBorder(null);

        nameValueLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        nameValueLabel.setToolTipText("");
        nameValueLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        nameValueLabel.setBorder(null);

        storeValueLabel.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        storeValueLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        storeValueLabel.setBorder(null);

        longDescriptionValueLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        longDescriptionValueLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        longDescriptionValueLabel.setAlignmentY(0.0F);
        longDescriptionValueLabel.setBorder(null);

        categoryLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        categoryLabel.setText("Category:");

        weightValueLabel.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        weightValueLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        weightValueLabel.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(longDescriptionValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shortDescriptionValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(117, 117, 117)
                            .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(571, 571, 571)
                            .addComponent(AddToCartButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(longDescriptionLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(nameLabel)
                            .addGap(66, 66, 66)
                            .addComponent(nameValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 401, Short.MAX_VALUE)
                        .addComponent(priceLabel)
                        .addGap(18, 18, 18)
                        .addComponent(priceValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addComponent(shortDescriptionLabel)
                    .addComponent(weightLabel)))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryLabel)
                    .addComponent(storeLabel))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(categoryValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                        .addComponent(weightValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(storeValueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(storeLabel)
                            .addComponent(storeValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(categoryLabel)
                            .addComponent(categoryValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(weightLabel)
                    .addComponent(weightValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(shortDescriptionLabel)
                .addGap(18, 18, 18)
                .addComponent(shortDescriptionValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(longDescriptionLabel)
                .addGap(36, 36, 36)
                .addComponent(longDescriptionValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(AddToCartButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToCartButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddToCartButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCartButton;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel categoryValueLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel longDescriptionLabel;
    private javax.swing.JLabel longDescriptionValueLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameValueLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceValueLabel;
    private javax.swing.JLabel shortDescriptionLabel;
    private javax.swing.JLabel shortDescriptionValueLabel;
    private javax.swing.JLabel storeLabel;
    private javax.swing.JLabel storeValueLabel;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JLabel weightValueLabel;
    // End of variables declaration//GEN-END:variables
}
