/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.view;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import mvc.controller.ConnectionHandler;

/**
 *
 * @author bohao
 */
public class RegisterPage extends javax.swing.JFrame {
	
	/**
	 * Creates new form RegisterPage
	 */
	public RegisterPage() {
		initComponents();
		init();
	}

	private void init() {
		setLocationRelativeTo(null);
		setResizable(false);
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        df = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        firstLine = new javax.swing.JTextField();
        secondLine = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        zipCode = new javax.swing.JTextField();
        country = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        country1 = new javax.swing.JLabel();
        complement = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(48, 148, 209));
        jLabel1.setText("Registration");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel2.setText("First name:");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setText("Last name:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel5.setText("Phone number:");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel6.setText("User name:");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(148, 38, 161));
        jLabel7.setText("Address:");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel8.setText("First line:");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel9.setText("City:");

        df.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        df.setText("Country:");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel11.setText("Second line:");

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel12.setText("Zip code:");

        userName.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });

        firstName.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });

        lastName.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });

        email.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        phone.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });

        firstLine.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        firstLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstLineActionPerformed(evt);
            }
        });

        secondLine.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        secondLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondLineActionPerformed(evt);
            }
        });

        city.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });

        zipCode.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        zipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipCodeActionPerformed(evt);
            }
        });

        country.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        submit.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        country1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        country1.setText("Address complement");

        complement.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        complement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(country1)
                            .addComponent(jLabel12)
                            .addComponent(df))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstLine)
                            .addComponent(secondLine)
                            .addComponent(city)
                            .addComponent(zipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(country)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(userName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                .addComponent(firstName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lastName, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(email)
                            .addComponent(jLabel1)
                            .addComponent(complement, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(submit)
                        .addGap(117, 117, 117)
                        .addComponent(clear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(firstLine, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(secondLine, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(zipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(df)
                    .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(country1)
                    .addComponent(complement, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear)
                    .addComponent(submit))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void firstLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstLineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstLineActionPerformed

    private void secondLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondLineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondLineActionPerformed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityActionPerformed

    private void zipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipCodeActionPerformed

    private void countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        userName.setText("");
		firstName.setText("");
		lastName.setText("");
		email.setText("");
		phone.setText("");
		firstLine.setText("");
		secondLine.setText("");
		city.setText("");
		zipCode.setText("");
		df.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
		if (userName.getText().isEmpty()
				|| firstName.getText().isEmpty()
				|| lastName.getText().isEmpty()
				|| email.getText().isEmpty()
				|| phone.getText().isEmpty()
				|| firstLine.getText().isEmpty()
				|| city.getText().isEmpty()
				|| zipCode.getText().isEmpty()
				|| df.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null,
					"please complete the form",
					"Error", JOptionPane.ERROR_MESSAGE);
			return;
		}
		
		// must mathc user name format
		if (!userName.getText().matches("[A-Za-z0-9_]+")) {
			JOptionPane.showMessageDialog(null,
					"in valid user name, you can only"
					+ " use letters, digits, underscore or hyphen ",
					"Error", JOptionPane.ERROR_MESSAGE);
			return;
		}

		// must match phone number format
		if (!phone.getText().matches("[0-9*#+-]+")) {
			JOptionPane.showMessageDialog(null,
					"phone number can only contain digits, asterisk, "
					+ "sharp or plus",
					"Error", JOptionPane.ERROR_MESSAGE);
			return;
		}
		
		ResultSet rs = ConnectionHandler.getResultSet(
				"SELECT * FROM customer");
		
		// check if user name already exists
		try {
			while (rs.next()) {
				if (userName.getText().equals(rs.getString("user_name"))) {
					JOptionPane.showMessageDialog(null,
							"User name already exist",
							"Error", JOptionPane.ERROR_MESSAGE);
					return;
				}
			}
		} catch (SQLException | HeadlessException e) {
			e.printStackTrace(System.out);
		}

		String queryInsertCustomer
				= "INSERT INTO `customer` "
				+ "(`id`, "
				+ "`user_name`, "
				+ "`first_name`, "
				+ "`last_name`, "
				+ "`email_address`, "
				+ "`phone_number`, "
				+ "`has_address`, "
				+ "`has_shopping_list`, "
				+ "`has_order`, "
				+ "`active`) "
				+ "VALUES ("
				+ "NULL, "
				+ "'" + userName.getText() + "', "
				+ "'" + firstName.getText() + "', "
				+ "'" + lastName.getText() + "', "
				+ "'" + email.getText() + "', "
				+ "'" + phone.getText() + "', "
				+ "'Y', "
				+ "'N',"
				+ " 'N', "
				+ "'Y')";
		ConnectionHandler.executeUpdate(queryInsertCustomer);
		
		rs = ConnectionHandler.getResultSet(
				"SELECT * FROM customer "
						+ "WHERE user_name='" + userName.getText() + "'");
		String customerId = null;
		// get the id of the customer
		try {
			rs.next();
			customerId = rs.getString("id");
		} catch (Exception e) {
			e.printStackTrace(System.out);
		}
		
		String queryInsertAddress = 
				"INSERT INTO `address` ("
				+ "`id`, "
				+ "`customer_id`, "
				+ "`address_line_1`, "
				+ "`address_line_2`, "
				+ "`city`, "
				+ "`country`, "
				+ "`zip_code`, "
				+ "`address_complement`, "
				+ "`is_address_by_default`, "
				+ "`active`) "
				+ "VALUES ("
				+ "NULL, "
				+ customerId + ", "
				+ "'" + firstLine.getText() + "', "
				// the second line of the address can be null
				+ (secondLine.getText().isEmpty() ?
					"NULL, " : 
					("'" + secondLine.getText() + "', "))
				+ "'" + city.getText() + "', "
				+ "'" + country.getText() + "', "
				+ "'" + zipCode.getText() + "', "
				// the complement of the address can be null
				+ (complement.getText().isEmpty() ? 
					"NULL, " : 
					("'" + complement.getText() + "', "))
				+ "'N', 'Y')";
		
		ConnectionHandler.executeUpdate(queryInsertAddress);
		dispose();
		JOptionPane.showMessageDialog(null,
				"Registration finished, you can now login as customer");
		new LoginPage().setVisible(true);
		
    }//GEN-LAST:event_submitActionPerformed

    private void complementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complementActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField city;
    private javax.swing.JButton clear;
    private javax.swing.JTextField complement;
    private javax.swing.JTextField country;
    private javax.swing.JLabel country1;
    private javax.swing.JLabel df;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstLine;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField secondLine;
    private javax.swing.JButton submit;
    private javax.swing.JTextField userName;
    private javax.swing.JTextField zipCode;
    // End of variables declaration//GEN-END:variables
}
